name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
        - '**'
  pull_request:
    branches:
      - '**'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Test - Ubuntu (Python 3.10, Intel)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      os: Ubuntu
      arch: Intel
    steps:
    - name: Clean workspace
      uses: Chia-Network/actions/clean-workspace@main

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: Chia-Network/actions/setup-python@main
      with:
        python-version: '3.10'

    - name: Copy pre-generated plots
      run: |
        mkdir -p ~/.chia/simulator/plots
        cp -r ./.github/test-plots/* ~/.chia/simulator/plots

    - uses: Chia-Network/actions/create-venv@main
      id: create-venv

    - uses: Chia-Network/actions/activate-venv@main
      with:
        directories: ${{ steps.create-venv.outputs.activate-venv-directories }}

    - name: Setup chia-dev-tools
      run: |
        git clone https://github.com/Chia-Network/chia-dev-tools.git
        cd chia-dev-tools
        pip install .
        cd ..

    - name: Initialize chia
      run: chia init

    - name: Test code with pytest
      run: pytest tests/ -s -v --durations 0
